# Generated by Django 6.0.3 on 2026-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='prodi',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='github',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='order',
        ),
        migrations.AddField(
            model_name='member',
            name='npm',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='accent_color',
            field=models.CharField(default='#F5AFAF', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='bg_color',
            field=models.CharField(default='#FCF8F8', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='card_color',
            field=models.CharField(default='#FBEFEF', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='font_family',
            field=models.CharField(default='Outfit', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='text_color',
            field=models.CharField(default='#4a044e', max_length=20),
        ),
    ]
